package th.ac.kmutnb.prachin.map.data.model

/**
 * The tones that ship with the app.
 *
 * Two of them, with different jobs rather than different decorations: one that says "look
 * up" and one that says "stop". Adding a third is cheap, but every extra choice is one the
 * person marking a hazard has to make while standing next to it, so the list stays short
 * for the same reason [HazardType] does.
 *
 * `id` is what goes in the database and in the exported file, so it has to survive the
 * enum being renamed.
 */
enum class BundledHazardSound(val id: String, val fileName: String) {
    /** A soft two-note rise. Noticed without being alarming. */
    CHIME("bundled:chime", "hazard_chime"),

    /** Three short pulses above traffic noise. For something to stop for. */
    ALERT("bundled:alert", "hazard_alert"),
    ;

    companion object {
        fun fromId(id: String?): BundledHazardSound? = entries.firstOrNull { it.id == id }
    }
}

/** Where a sound's audio lives, which is also how long it lasts and how far it travels. */
enum class HazardSoundOrigin {
    /**
     * A tone generated by `tools/make_alert_sounds.py` and compiled into `res/raw`.
     * Always present on every install, which is what makes it safe as a fallback.
     */
    BUNDLED,

    /**
     * An audio file dropped into `assets/sounds/` before the app was built.
     *
     * The way to give everyone the same warning sounds: it ships inside the APK, so its
     * id means the same thing on every phone running this build, and a `hazards.geojson`
     * that names one still names it after being shared.
     */
    ASSET,

    /**
     * A file the user picked on their own phone, copied into app storage.
     * Never leaves that phone, so a hazard file naming one falls back elsewhere.
     */
    IMPORTED,
}

/**
 * A sound that can be played ahead of a hazard warning.
 *
 * One flat type for all three origins, because everything downstream - the picker, the
 * player, the stored id - treats them the same. [origin] decides where [fileName] points:
 * a raw resource, a file inside `assets/sounds/`, or a file in the app's own storage.
 */
data class HazardSound(
    val id: String,
    /**
     * What to call it in the picker. Empty for a bundled tone, whose name is a Thai string
     * resource rather than stored text - see `ui/common/Messages.kt`.
     */
    val name: String,
    val origin: HazardSoundOrigin,
    val fileName: String,
    val addedAt: Long,
) {
    /** Only an imported sound can be removed; the other two are part of the build. */
    val isRemovable: Boolean get() = origin == HazardSoundOrigin.IMPORTED

    companion object {
        /** The bundled tones, in picker order. Always available, on every device. */
        val bundled: List<HazardSound> = BundledHazardSound.entries.map { tone ->
            HazardSound(
                id = tone.id,
                name = "",
                origin = HazardSoundOrigin.BUNDLED,
                fileName = tone.fileName,
                addedAt = 0L,
            )
        }

        /** Prefix of an [HazardSoundOrigin.ASSET] id: `asset:siren.mp3`. */
        const val ASSET_ID_PREFIX = "asset:"

        /**
         * The audio formats accepted from `assets/sounds/`.
         *
         * Limited to the ones Android leaves uncompressed in the APK, because the player
         * opens them with `openFd`, which fails on a compressed asset. Anything else in
         * the folder is ignored rather than offered and then found unplayable outdoors.
         */
        val ASSET_EXTENSIONS: Set<String> = setOf("mp3", "ogg", "wav", "m4a", "aac", "opus")

        /**
         * Turns a file name from `assets/sounds/` into a sound, or null if it is not
         * audio this build can open.
         */
        fun fromAssetFileName(fileName: String): HazardSound? {
            val extension = fileName.substringAfterLast('.', "").lowercase()
            if (extension !in ASSET_EXTENSIONS) return null
            return HazardSound(
                id = ASSET_ID_PREFIX + fileName,
                name = fileName.substringBeforeLast('.'),
                origin = HazardSoundOrigin.ASSET,
                fileName = fileName,
                addedAt = 0L,
            )
        }
    }
}

/**
 * Which tone a hazard uses, when the person marking it did not choose one.
 *
 * Tied to severity rather than being one tone for everything, so that the sound carries
 * the same information the warning distance does: a walker who has heard both learns which
 * one means "step around it" and which means "stop", and gets that in the third of a
 * second before the sentence starts.
 */
val HazardSeverity.defaultSound: BundledHazardSound
    get() = when (this) {
        HazardSeverity.CAUTION -> BundledHazardSound.CHIME
        HazardSeverity.WARNING -> BundledHazardSound.CHIME
        HazardSeverity.DANGER -> BundledHazardSound.ALERT
    }

/**
 * The file name in `assets/sounds/` that takes over this severity's default, if present.
 *
 * The whole point of dropping files in: name one `default_danger.mp3` and every hazard
 * that never chose a sound of its own now uses it, with nothing to configure and no UI to
 * find. The generated tone stays as the fallback for when no such file was shipped.
 */
val HazardSeverity.defaultAssetBaseName: String
    get() = when (this) {
        HazardSeverity.CAUTION -> "default_caution"
        HazardSeverity.WARNING -> "default_warning"
        HazardSeverity.DANGER -> "default_danger"
    }

/**
 * The id [HazardPoint.soundId] carries when the hazard is meant to be spoken without a
 * tone in front of it.
 *
 * Needed as a real value rather than as null, because null already means "whatever suits
 * the severity" - which is what every hazard marked before sounds existed means, and what
 * someone who never opened the sound picker meant.
 */
const val HAZARD_SOUND_NONE = "none"

/**
 * Picks the sound to play for [hazard], or null to play none.
 *
 * [available] is the whole catalogue: the bundled tones plus whatever has been imported on
 * this device.
 *
 * An id that is not in the catalogue falls back to the severity's default instead of going
 * silent. That is the normal case for a shared file, not an error - hazards travel between
 * phones as `hazards.geojson`, and the tone a surveyor imported onto their own phone does
 * not travel with it. Dropping the sound would be defensible; dropping it quietly on the
 * hazards someone bothered to customise is the wrong half to lose.
 */
fun resolveHazardSound(hazard: HazardPoint, available: List<HazardSound>): HazardSound? {
    if (hazard.soundId == HAZARD_SOUND_NONE) return null
    hazard.soundId?.let { id ->
        available.firstOrNull { it.id == id }?.let { return it }
    }
    // A dropped-in default_<severity>.* wins over the generated tone; the tone is what
    // is left when nobody shipped one, which is why it can never itself be missing.
    val override = hazard.severity.defaultAssetBaseName
    available.firstOrNull {
        it.origin == HazardSoundOrigin.ASSET && it.fileName.substringBeforeLast('.') == override
    }?.let { return it }

    val fallback = hazard.severity.defaultSound.id
    return available.firstOrNull { it.id == fallback }
        ?: HazardSound.bundled.firstOrNull { it.id == fallback }
}
