package th.ac.kmutnb.prachin.map.core.sound

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.net.Uri
import android.util.Log
import th.ac.kmutnb.prachin.map.R
import th.ac.kmutnb.prachin.map.data.assets.AssetPaths
import th.ac.kmutnb.prachin.map.data.model.BundledHazardSound
import th.ac.kmutnb.prachin.map.data.model.HazardSound
import th.ac.kmutnb.prachin.map.data.model.HazardSoundOrigin
import th.ac.kmutnb.prachin.map.data.repository.HazardSoundRepository
import java.io.File

/** The raw resource behind each bundled tone. Generated by `tools/make_alert_sounds.py`. */
val BundledHazardSound.rawResId: Int
    get() = when (this) {
        BundledHazardSound.CHIME -> R.raw.hazard_chime
        BundledHazardSound.ALERT -> R.raw.hazard_alert
    }

/**
 * Plays the short tone that goes in front of a spoken hazard warning.
 *
 * The tone is not decoration. Speech takes a moment to start and a second or two to say
 * anything, and it competes with traffic; a tone arrives immediately, survives noise, and
 * is understood before the sentence begins. It is also what still reaches someone whose
 * phone has no Thai voice data, which is common enough on budget devices that the app
 * already has a message about it.
 *
 * Nothing here decides *when* to warn. The tone plays exactly when the spoken warning
 * would have, on the transitions [th.ac.kmutnb.prachin.map.navigation.HazardMonitor]
 * allows and no others - a sound that fires more often than the voice would be the
 * fastest possible way to get the whole warning system muted.
 *
 * Prepared asynchronously, so a slow read of an imported file cannot stall the frame that
 * is drawing the warning banner at the same moment.
 */
class HazardSoundPlayer(context: Context) {

    private val appContext = context.applicationContext

    private var current: MediaPlayer? = null

    /**
     * Plays [sound], then calls [onFinished] on the thread the player reports back on.
     *
     * [onFinished] runs exactly once, whatever happens - including when the file turns out
     * to be undecodable. It carries the spoken warning, and dropping the sentence because
     * a tone failed would trade the informative half of the warning for the decorative
     * one.
     *
     * A sound already playing is replaced: warnings arrive one at a time and the newest is
     * the one worth hearing. The replaced sound's callback does not run, because its
     * sentence has been superseded too.
     */
    fun play(sound: HazardSound, onFinished: () -> Unit = {}) {
        release()
        var finished = false
        val player = MediaPlayer()
        current = player

        fun finish() {
            if (finished) return
            finished = true
            onFinished()
        }

        fun done(it: MediaPlayer) {
            if (current === it) current = null
            runCatching { it.release() }
        }

        runCatching {
            player.setAudioAttributes(NAVIGATION_GUIDANCE)
            setSource(player, sound)
            player.setOnPreparedListener { it.start() }
            player.setOnCompletionListener { finish(); done(it) }
            player.setOnErrorListener { it, what, extra ->
                Log.w(TAG, "playing the hazard sound failed, what=$what extra=$extra")
                finish()
                done(it)
                true
            }
            player.prepareAsync()
        }.onFailure { error ->
            Log.w(TAG, "could not start the hazard sound", error)
            finish()
            done(player)
        }
    }

    /** Stops whatever is playing. No callback runs; the warning it belonged to is over. */
    fun release() {
        val player = current ?: return
        current = null
        runCatching {
            player.setOnCompletionListener(null)
            player.setOnErrorListener(null)
            player.reset()
            player.release()
        }
    }

    /**
     * Points the player at wherever this sound's audio actually is.
     *
     * Three places, one per origin. An asset is opened as a file descriptor into the APK
     * rather than through a URI, which is why `assets/sounds/` only accepts the formats
     * Android leaves uncompressed - `openFd` cannot open a compressed entry.
     *
     * Throws if the audio has gone. The caller treats that the same as a failure to play:
     * the warning is still spoken, because losing the sentence over a missing tone would
     * trade the informative half of the warning for the decorative one.
     */
    private fun setSource(player: MediaPlayer, sound: HazardSound) {
        when (sound.origin) {
            HazardSoundOrigin.BUNDLED -> {
                val tone = requireNotNull(BundledHazardSound.fromId(sound.id)) {
                    "no bundled tone with id ${sound.id}"
                }
                val uri = Uri.parse("android.resource://${appContext.packageName}/${tone.rawResId}")
                player.setDataSource(appContext, uri)
            }

            HazardSoundOrigin.ASSET -> {
                appContext.assets
                    .openFd("${AssetPaths.HAZARD_SOUNDS_DIR}/${sound.fileName}")
                    .use { descriptor ->
                        player.setDataSource(
                            descriptor.fileDescriptor,
                            descriptor.startOffset,
                            descriptor.length,
                        )
                    }
            }

            HazardSoundOrigin.IMPORTED -> {
                val file = File(HazardSoundRepository.soundsDir(appContext), sound.fileName)
                require(file.exists()) { "imported sound ${sound.fileName} has gone" }
                player.setDataSource(appContext, Uri.fromFile(file))
            }
        }
    }

    private companion object {
        const val TAG = "HazardSoundPlayer"

        /**
         * The same usage the spoken warning uses: music ducks instead of stopping, and the
         * tone still plays with the phone in a pocket and the screen off.
         */
        val NAVIGATION_GUIDANCE: AudioAttributes = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_ASSISTANCE_NAVIGATION_GUIDANCE)
            .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
            .build()
    }
}
