package th.ac.kmutnb.prachin.map.core.sound

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.net.Uri
import android.util.Log
import th.ac.kmutnb.prachin.map.R
import th.ac.kmutnb.prachin.map.data.model.BundledHazardSound
import th.ac.kmutnb.prachin.map.data.model.HazardSound
import th.ac.kmutnb.prachin.map.data.repository.HazardSoundRepository
import java.io.File

/** The raw resource behind each bundled tone. Generated by `tools/make_alert_sounds.py`. */
val BundledHazardSound.rawResId: Int
    get() = when (this) {
        BundledHazardSound.CHIME -> R.raw.hazard_chime
        BundledHazardSound.ALERT -> R.raw.hazard_alert
    }

/**
 * Plays the short tone that goes in front of a spoken hazard warning.
 *
 * The tone is not decoration. Speech takes a moment to start and a second or two to say
 * anything, and it competes with traffic; a tone arrives immediately, survives noise, and
 * is understood before the sentence begins. It is also what still reaches someone whose
 * phone has no Thai voice data, which is common enough on budget devices that the app
 * already has a message about it.
 *
 * Nothing here decides *when* to warn. The tone plays exactly when the spoken warning
 * would have, on the transitions [th.ac.kmutnb.prachin.map.navigation.HazardMonitor]
 * allows and no others - a sound that fires more often than the voice would be the
 * fastest possible way to get the whole warning system muted.
 *
 * Prepared asynchronously, so a slow read of an imported file cannot stall the frame that
 * is drawing the warning banner at the same moment.
 */
class HazardSoundPlayer(context: Context) {

    private val appContext = context.applicationContext

    private var current: MediaPlayer? = null

    /**
     * Plays [sound], then calls [onFinished] on the thread the player reports back on.
     *
     * [onFinished] runs exactly once, whatever happens - including when the file turns out
     * to be undecodable. It carries the spoken warning, and dropping the sentence because
     * a tone failed would trade the informative half of the warning for the decorative
     * one.
     *
     * A sound already playing is replaced: warnings arrive one at a time and the newest is
     * the one worth hearing. The replaced sound's callback does not run, because its
     * sentence has been superseded too.
     */
    fun play(sound: HazardSound, onFinished: () -> Unit = {}) {
        val uri = uriFor(sound)
        if (uri == null) {
            onFinished()
            return
        }

        release()
        var finished = false
        val player = MediaPlayer()
        current = player

        fun finish() {
            if (finished) return
            finished = true
            onFinished()
        }

        fun done(it: MediaPlayer) {
            if (current === it) current = null
            runCatching { it.release() }
        }

        runCatching {
            player.setAudioAttributes(NAVIGATION_GUIDANCE)
            player.setDataSource(appContext, uri)
            player.setOnPreparedListener { it.start() }
            player.setOnCompletionListener { finish(); done(it) }
            player.setOnErrorListener { it, what, extra ->
                Log.w(TAG, "playing the hazard sound failed, what=$what extra=$extra")
                finish()
                done(it)
                true
            }
            player.prepareAsync()
        }.onFailure { error ->
            Log.w(TAG, "could not start the hazard sound", error)
            finish()
            done(player)
        }
    }

    /** Stops whatever is playing. No callback runs; the warning it belonged to is over. */
    fun release() {
        val player = current ?: return
        current = null
        runCatching {
            player.setOnCompletionListener(null)
            player.setOnErrorListener(null)
            player.reset()
            player.release()
        }
    }

    /**
     * Where the audio actually is: a raw resource for a bundled tone, a file in the app's
     * own storage for an imported one.
     *
     * Null when an imported sound's file has gone - which should not happen, since the app
     * owns that directory, but a missing file must mean "speak without a tone" rather than
     * an exception thrown while someone walks towards a road.
     */
    private fun uriFor(sound: HazardSound): Uri? {
        if (sound.isBundled) {
            val tone = BundledHazardSound.fromId(sound.id) ?: return null
            return Uri.parse("android.resource://${appContext.packageName}/${tone.rawResId}")
        }
        val file = File(HazardSoundRepository.soundsDir(appContext), sound.fileName)
        return if (file.exists()) Uri.fromFile(file) else null
    }

    private companion object {
        const val TAG = "HazardSoundPlayer"

        /**
         * The same usage the spoken warning uses: music ducks instead of stopping, and the
         * tone still plays with the phone in a pocket and the screen off.
         */
        val NAVIGATION_GUIDANCE: AudioAttributes = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_ASSISTANCE_NAVIGATION_GUIDANCE)
            .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
            .build()
    }
}
